### ISSUE TITLE
Note to self: Use v8 intrinsics instead of readIntXX and readUintXX

### ISSUE THREAD

**Issue by bkw** [felixge/node-buffy#11]
From https://groups.google.com/d/topic/nodejs/CnM53h1CiFU/discussion talking about readUInt8():

> Don't use buf.readUInt8(), it's only there for the sake of parity with 
> the other .readUInt*() functions. Replace it with `a = buf[b]` and 
> you'll see a 4-5x speed-up. 

and about the rest of readUIntXX and readIntXX:

> they're there mostly for convenience*. If you need to read 
> in e.g. a little-endian short, do this: 
> 
> v = buf[i] | (buf[i + 1] << 8); 
> 
> Same but big-endian: 
> 
>  v = (buf[i] << 8) | buf[i + 1];

**Comment by bkw** [comment]
notes from some naive benchmarking readUInt8 and readUInt16:
- intrinsics with no boundary checks are the fastest, on par with arrays.
- buffer methods are dead slow, even with assert false
- asserts are much slower that ifs
- two ifs are not slower than checking for two or'ed conditions
- out-of-bounds access on buffers returns undefined, might be sufficient
- (a == null) is slower than (a === null || a=== undefined)

**Comment by felixge** [comment]
Oh yeah, in node-mysql I have all non-float stuff implemented via buffer array access as well right now. So this needs to be done in buffy for performance.

**Comment by bkw** [comment]
Continued in #14
