### ISSUE TITLE
enable travis

### ISSUE THREAD

**Issue by bkw** [felixge/node-buffy#15]
@felixge it seems node-buffy is not enabled in your travis account. Could You flip the switch please? Thanks!

**Comment by felixge** [comment]
Done! Would be cool if you could add the banner image for it!

**Comment by felixge** [comment]
Unrelated: Do you know at what time your talk is tomorrow? I may not be able to come for the full BerlinJS, but I could try to stop by for your presentation.

**Comment by bkw** [comment]
I think my talk will be the first one, so it should start sevenish.
Damn, I still have to prepare slides....

**Comment by bkw** [comment]
you should really try to make it, I have a surprise especially for you.
Ahhh, the suspense....

**Comment by felixge** [comment]
@bkw ok, I'll try to be there. Would be great if you're first, maybe @rmehner can arrange for it?

Anyway, we could probably have a beer and chat for a bit while the other talks are going on, but I'll have to leave before they finish.

**Comment by rmehner** [comment]
Talks start at 7:30 anyway. What time do you have in mind @felixge?

**Comment by felixge** [comment]
@rmehner no particular time, I just didn't have a quite evening with the girlfriend for 2 weeks now, so I was hoping to have some of that tomorrow. 7:30 works.

**Comment by bkw** [comment]
https://travis-ci.org/felixge/node-buffy :ok_hand:

**Comment by bkw** [comment]
Thanks.
btw: this is really neat: https://github.com/travis-ci/travis-watcher-macosx
