### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bkw** [felixge/node-buffy#7]
I think the current version is better that 0.0.3 in all aspects. Also I could drop my private references from nodecopter-stream if there was a new official version.

**Comment by felixge** [comment]
Here is a better idea: I just added you as a collaborator on github and package author on npm. So feel free to tag a new version (using `npm version 0.0.4`) and publish it!

Thank you so much for your help!

**Comment by bkw** [comment]
wow, thanks!

I did an npm publish, and it seems to have worked, but it doesn't show up on npmjs.org yet.
Will check later (real life calling). Thanks again! You're awesome!

**Comment by felixge** [comment]
The npm publish seems to have worked:

``` bash
$ npm info buffy
npm http GET https://registry.npmjs.org/buffy
npm http 200 https://registry.npmjs.org/buffy

{ name: 'buffy',
  description: 'A module to read / write binary data and streams.',
  'dist-tags': { latest: '0.0.4' },
...
```

However, it seems like you did not create / publish the tag for the new release. Try:

``` bash
git push --tags
```

>  Thanks again! You're awesome!

Nope, you're doing the work here - thank you so much for your help! : )

Cheers,
Felix
