### ISSUE TITLE
Writable Stream needs to implement `end` method

### ISSUE THREAD

**Issue by donpark** [felixge/node-buffy#9]
Not sure when this requirement was added but using Buffy on node 0.8.12 results in:

```
 TypeError: Object #<Reader> has no method 'end'
  at onend (stream.js:66:10)
  at EventEmitter.emit (events.js:123:20)
  at afterRead (fs.js:1327:12)
  at Object.wrapper [as oncomplete] (fs.js:362:17)
```

because `Stream` module [expects writable streams to have `end` method implemented](https://github.com/joyent/node/blob/master/lib/stream.js#L66).

Workaround is to call `stream.pipe` with `end: false` option.

**Comment by donpark** [comment]
Nevermind. Example code using `data` event and `pipe` method led me to think Buffy `Reader` was a `Stream` when it actually isn't.

**Comment by bkw** [comment]
I prepared a patch that actually does make it a stream. I'm still waiting to hear from felix about it (felixge/node-buffy#10) but could you give the branch a test run with your test case? Would be much appreciated.

**Comment by donpark** [comment]
hi @bkw, my workaround in [`wave-reader`](https://github.com/donpark/wave-reader) is working just fine for now but I'll give your patch a try when I get some free time. thx.

**Comment by bkw** [comment]
@donpark nice! Have You seen [node-wav](https://github.com/TooTallNate/node-wav) ? Maybe the two of you should team up.

**Comment by donpark** [comment]
yup. not sure about teaming up with him but I can definitely use him as my excuse to leave my own project unmaintained. ;-p
